name: Build Binaries

on:
  push:
    paths-ignore:
      - '.github/*'
      - '*.md'
  pull_request:
    paths-ignore:
      - '.github/*'
      - '*.md'

jobs:
  build:
    runs-on: windows-11-arm
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Apply Patches
      shell: cmd
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        apply-patches.bat
    - name: Build x86
      shell: cmd
      run: onekey-build-x86.bat
    - name: Build x64
      shell: cmd
      run: onekey-build-x64.bat
    - name: Build ARM64
      shell: cmd
      run: onekey-build-arm64.bat
    - uses: actions/upload-artifact@v4
      with:
        name: halalcloud-qt-binaries
        path: Output\Binaries
